name: bicycle_obu
description: Cross-platform bicycle OBU dashboard and ESP32-S3 BLE client.
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: 8.3.1
  crypto: ^3.0.6
  cross_file: ^0.3.4+2
  file_picker: ^10.3.3
  flutter_secure_storage: ^9.2.4
  geolocator: 14.0.3
  http: 1.6.0
  latlong2: 0.10.1
  mqtt_client: ^10.11.11
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  sensors_plus: 7.1.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.5
  universal_ble: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
